receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024
  
  attributes:
    actions:
      - key: loki.attribute.labels
        value: service_name, event_type, agent_id, severity, category, exploit_id, file_path, depth, state
        action: insert

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  logging:
    loglevel: info

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [loki, logging]

